name: otter-grader
channels: 
    - conda-forge
    - defaults
dependencies:
    - python>=3.6
    - r-base
    - r-essentials
    - r-devtools
    - pip
    - pip:
        - -r file:requirements.txt
        - -r file:requirements-test.txt
        - -r file:docs/requirements.txt
