name: {{ otter_env_name }}
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - nb_conda_kernels
    - r-base 
    - r-essentials 
    - r-devtools
    - libgit2
    - pip:
        - -r file:requirements.txt
