name: otter-env
channels:
  - defaults
  - conda-forge
  - r
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - gcc_linux-64
  - gxx_linux-64
  - libgit2
  - libgomp
  - r-base>=4.0.0
  - r-devtools
  - r-essentials
  - r-gert
  - r-rmarkdown
  - r-startup
  - r-stringi
  - r-testthat
  - r-usethis
  - r-ottr==1.5.0
  - pip:
      - otter-grader[grading,plugins,r]==6.0.4
