name: otter-env
channels:
  - defaults
  - conda-forge
  - r
dependencies:
  - python=3.12
  - pip
  - nb_conda_kernels
  - r-base>=4.0.0
  - r-essentials
  - r-devtools
  - libgit2
  - libgomp
  - r-gert
  - r-usethis
  - r-testthat
  - r-startup
  - r-rmarkdown
  - r-stringi
  - r-ottr==1.5.0
  - pip:
      - datascience
      - jupyter_client
      - ipykernel
      - matplotlib
      - pandas
      - ipywidgets
      - scipy
      - seaborn
      - scikit-learn
      - jinja2
      - nbconvert
      - nbformat
      - dill
      - numpy
      - gspread
      - otter-grader[export,grading,plugins]==5.6.0
      - rpy2
