name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number'
        required: true

jobs:
  build:
    if: contains('["chrispyles"]', github.actor)

    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Only allow releases off of master
        run: |
          python3 -c 'import os, sys; sys.exit(os.environ["GITHUB_REF"] != "refs/heads/master")'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt twine wheel setuptools

      - name: Update versions
        run: |
          python3 release.py ${{ github.event.inputs.version }}

      - name: Build tutorial
        run: |
          make tutorial

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git commit -am 'release v${{ github.event.inputs.version }}'
          git push --set-upstream origin release

      - name: Create dist and push to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*

      - name: Create a release on GitHub
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            hub release create -a dist/*.tar.gz -a dist/*.whl -t release \
            -m 'v${{ github.event.inputs.version }}' 'v${{ github.event.inputs.version }}'

      - name: Create a latest tag
        run: |
          git tag -f latest
          git push --force origin latest

      - name: PR release -> main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -b ucbds-infra:master -h ucbds-infra:release -l "release" -r chrispyles \
            -m "Release v${{ github.event.inputs.version }}"$'\n'$'\n'"Updates from the release of version ${{ github.event.inputs.version }}"
